### ISSUE TITLE
Cannot fold anymore

### ISSUE THREAD

**Issue by kapitanluffy** [predragnikolic/InlineFold#10]
![inline-fold-broken](https://github.com/predragnikolic/InlineFold/assets/485799/93d74b2a-32cb-4a65-a7b1-cc74546f14b8)

So doing the `fold` command (`Ctrl+Shift+[`) won't work anymore. It also breaks on non-xml files (JS, TS).

**Comment by predragnikolic** [comment]
I created a fix for the fold issue,
InlineFold will no longer try to unfold regions if the `fold` command was invoked.

```py
    def on_text_command(self, command: str, _args: dict) -> None:
        if (command == 'fold'):
            self.skip_folding = True
```

When you press `Ctrl+Shift+[` to fold, you should no longer experience the issue.

----

I noticed a ST bug.
If you open the command palette
and select the `Fold` command,
you will still hit experience this issue
because the on_text_command hook is **not called** (but I expect that ST calls this hook).

I do not plan to fix that case when it is triggered from the command palette.

**Comment by predragnikolic** [comment]
>  It also breaks on non-xml files (JS, TS).

Can you be more specific and provide the current and expected behavior?


And thanks for the bug report.

**Comment by predragnikolic** [comment]
I've created a new release that includes the "Fold" fix.

**Comment by kapitanluffy** [comment]
> > It also breaks on non-xml files (JS, TS).
> 
> Can you be more specific and provide the current and expected behavior?
> 
> And thanks for the bug report.

So normally `attributes` can only be seen in xml syntaxes (HTML, JSX, TSX, XML) but when I fold in Typescript, the bug happens (though not always)

So I was thinking maybe just enable it on xml syntaxes.

![inline-fold-broken2](https://github.com/predragnikolic/InlineFold/assets/485799/26bdc69b-2c50-4fed-8c77-6fe451441855)

**Comment by predragnikolic** [comment]
Package Control still didn't pick up the new 0.0.5 release. (0.0.4 is still on PC)

Can you verify if this still happens once you upgrade to 0.0.5?

**Comment by kapitanluffy** [comment]
> Package Control still didn't pick up the new 0.0.5 release. (0.0.4 is still on PC)
> 
> Can you verify if this still happens once you upgrade to 0.0.5?

Sure 👍

**Comment by kapitanluffy** [comment]
Fixed!
